// pages/chat/index.vue
<template>
  <div class="min-h-screen">
    <!-- 顶部导航 -->
    <header class="bg-white/90 backdrop-blur-sm border-b border-gray-200 sticky top-0 z-50">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center h-16">
          <!-- Logo 和导航 -->
          <div class="flex items-center space-x-8">
            <NuxtLink to="/" class="text-2xl font-bold text-primary-600">
              🤖 DiFlow
            </NuxtLink>
            <nav class="flex space-x-6">
              <NuxtLink 
                to="/chat" 
                class="nav-link active"
              >
                💬 对话
              </NuxtLink>
              <NuxtLink 
                to="/workflow" 
                class="nav-link"
              >
                🔄 工作流
              </NuxtLink>
              <NuxtLink 
                to="/tools" 
                class="nav-link"
              >
                🛠️ 工具
              </NuxtLink>
            </nav>
          </div>

          <!-- 用户信息 -->
          <div class="flex items-center space-x-4">
            <a-dropdown>
              <a-button type="text" class="flex items-center space-x-2">
                <a-avatar :size="32" class="bg-primary-500">
                  {{ authStore.user?.username?.charAt(0).toUpperCase() }}
                </a-avatar>
                <span class="hidden sm:inline">{{ authStore.user?.username }}</span>
                <DownOutlined />
              </a-button>
              <template #overlay>
                <a-menu>
                  <a-menu-item key="logout" @click="handleLogout">
                    <LogoutOutlined />
                    退出登录
                  </a-menu-item>
                </a-menu>
              </template>
            </a-dropdown>
          </div>
        </div>
      </div>
    </header>

    <!-- 聊天主要内容 -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div class="flex h-[calc(100vh-12rem)]">
        <!-- 聊天历史侧边栏 -->
        <div class="w-80 bg-white/70 backdrop-blur-sm rounded-2xl p-4 mr-4">
          <div class="flex justify-between items-center mb-4">
            <h3 class="text-lg font-semibold text-gray-800">聊天历史</h3>
            <a-button
              type="primary"
              size="small"
              @click="startNewChat"
              class="btn-cartoon btn-primary"
            >
              新对话
            </a-button>
          </div>
          
          <div class="space-y-2 max-h-96 overflow-y-auto">
            <div
              v-for="chat in chatHistory"
              :key="chat.id"
              :class="[
                'p-3 rounded-xl cursor-pointer transition-all duration-200',
                currentChatId === chat.id
                  ? 'bg-primary-100 border-2 border-primary-300'
                  : 'bg-gray-50 hover:bg-gray-100'
              ]"
              @click="selectChat(chat.id)"
            >
              <div class="font-medium text-sm truncate">{{ chat.title }}</div>
              <div class="text-xs text-gray-500 mt-1">
                {{ formatDate(chat.updatedAt) }}
              </div>
            </div>
          </div>
        </div>

        <!-- 主聊天区域 -->
        <div class="flex-1 flex flex-col">
          <!-- 模型选择 -->
          <div class="bg-white/70 backdrop-blur-sm rounded-2xl p-4 mb-4">
            <div class="flex items-center space-x-4">
              <span class="text-sm font-medium text-gray-700">AI 模型：</span>
              <a-select
                v-model:value="selectedModel"
                style="width: 200px"
                class="rounded-xl"
              >
                <a-select-option value="deepseek-chat">
                  🧠 DeepSeek Chat
                </a-select-option>
              </a-select>
            </div>
          </div>

          <!-- 聊天消息区域 -->
          <div class="flex-1 bg-white/70 backdrop-blur-sm rounded-2xl p-4 mb-4 overflow-hidden">
            <div
              ref="messagesContainer"
              class="h-full overflow-y-auto space-y-4 pr-2"
            >
              <div
                v-for="message in currentMessages"
                :key="message.id"
                class="flex"
                :class="message.role === 'user' ? 'justify-end' : 'justify-start'"
              >
                <div
                  :class="[
                    'max-w-xs lg:max-w-md px-4 py-3 rounded-2xl',
                    message.role === 'user'
                      ? 'chat-bubble-user'
                      : 'chat-bubble-assistant'
                  ]"
                >
                  <div class="text-sm whitespace-pre-wrap">{{ message.content }}</div>
                  <div class="text-xs opacity-70 mt-2">
                    {{ formatTime(message.timestamp) }}
                  </div>
                </div>
              </div>
              
              <!-- 加载指示器 -->
              <div v-if="isLoading" class="flex justify-start">
                <div class="chat-bubble-assistant">
                  <div class="flex items-center space-x-2">
                    <a-spin size="small" />
                    <span class="text-sm">AI 正在思考...</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- 输入区域 -->
          <div class="bg-white/70 backdrop-blur-sm rounded-2xl p-4">
            <div class="flex space-x-3">
              <a-textarea
                v-model:value="inputMessage"
                placeholder="输入您的消息..."
                :rows="3"
                class="flex-1 input-cartoon resize-none"
                @keydown.enter.exact.prevent="sendMessage"
                @keydown.enter.shift.exact="() => {}"
              />
              <a-button
                type="primary"
                size="large"
                :loading="isLoading"
                :disabled="!inputMessage.trim()"
                @click="sendMessage"
                class="btn-cartoon btn-primary px-8"
              >
                发送
              </a-button>
            </div>
            <div class="text-xs text-gray-500 mt-2">
              按 Enter 发送，Shift + Enter 换行
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { DownOutlined, LogoutOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import type { ChatMessage, Chat } from '~/types'

// 页面元数据
definePageMeta({
  middleware: 'auth'
})

// 状态管理
const authStore = useAuthStore()

// 响应式数据
const inputMessage = ref('')
const selectedModel = ref('deepseek-chat')
const isLoading = ref(false)
const currentChatId = ref<string | null>(null)
const currentMessages = ref<ChatMessage[]>([])
const chatHistory = ref<Chat[]>([])
const messagesContainer = ref<HTMLElement>()

// 发送消息
const sendMessage = async () => {
  if (!inputMessage.value.trim() || isLoading.value) return

  const userMessage = inputMessage.value.trim()
  inputMessage.value = ''
  isLoading.value = true

  // 添加用户消息到界面
  const userMsg: ChatMessage = {
    id: crypto.randomUUID(),
    role: 'user',
    content: userMessage,
    timestamp: new Date().toISOString()
  }
  currentMessages.value.push(userMsg)

  // 滚动到底部
  nextTick(() => {
    scrollToBottom()
  })

  try {
    const response = await $fetch('/api/chat/send', {
      method: 'POST',
      headers: authStore.getAuthHeaders(),
      body: {
        message: userMessage,
        model: selectedModel.value,
        chatId: currentChatId.value
      }
    })

    if (response.success && response.data) {
      // 添加 AI 回复到界面
      currentMessages.value.push(response.data.message)
      currentChatId.value = response.data.chatId

      // 更新聊天历史
      await loadChatHistory()
    }
  } catch (error: any) {
    message.error(error.data?.message || '发送失败')
  } finally {
    isLoading.value = false
    nextTick(() => {
      scrollToBottom()
    })
  }
}

// 开始新对话
const startNewChat = () => {
  currentChatId.value = null
  currentMessages.value = []
}

// 选择聊天
const selectChat = async (chatId: string) => {
  try {
    const response = await $fetch(`/api/chat/${chatId}`, {
      headers: authStore.getAuthHeaders()
    })

    if (response.success && response.data) {
      currentChatId.value = chatId
      currentMessages.value = response.data.messages
      nextTick(() => {
        scrollToBottom()
      })
    }
  } catch (error: any) {
    message.error('加载聊天记录失败')
  }
}

// 加载聊天历史
const loadChatHistory = async () => {
  try {
    const response = await $fetch('/api/chat/history', {
      headers: authStore.getAuthHeaders()
    })

    if (response.success && response.data) {
      chatHistory.value = response.data
    }
  } catch (error: any) {
    console.error('加载聊天历史失败:', error)
  }
}

// 滚动到底部
const scrollToBottom = () => {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
  }
}

// 格式化日期
const formatDate = (dateString: string) => {
  const date = new Date(dateString)
  const now = new Date()
  const diff = now.getTime() - date.getTime()
  const days = Math.floor(diff / (1000 * 60 * 60 * 24))

  if (days === 0) {
    return '今天'
  } else if (days === 1) {
    return '昨天'
  } else if (days < 7) {
    return `${days}天前`
  } else {
    return date.toLocaleDateString()
  }
}

// 格式化时间
const formatTime = (dateString: string) => {
  return new Date(dateString).toLocaleTimeString('zh-CN', {
    hour: '2-digit',
    minute: '2-digit'
  })
}

// 处理登出
const handleLogout = () => {
  authStore.logout()
  message.success('已退出登录')
}

// 初始化
onMounted(() => {
  authStore.init()
  loadChatHistory()
})
</script>

<style scoped>
/* 导航链接样式 */
.nav-link {
  @apply px-4 py-2 rounded-xl text-gray-600 hover:text-primary-600 hover:bg-primary-50 transition-all duration-200 font-medium;
}

.nav-link.active {
  @apply text-primary-600 bg-primary-100;
}

/* 自定义样式 */
.ant-select {
  @apply rounded-xl;
}

:deep(.ant-select-selector) {
  @apply rounded-xl border-2 border-cute-purple/30;
}

:deep(.ant-textarea) {
  @apply input-cartoon;
}
</style>

// app/chat/page.tsx
'use client'

import { useState, useEffect, useRef } from 'react'

interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: string
}

interface Chat {
  id: string
  title: string
  updatedAt: string
  messages: ChatMessage[]
}

interface User {
  username: string
}

export default function ChatPage() {
  const [inputMessage, setInputMessage] = useState('')
  const [selectedModel, setSelectedModel] = useState('deepseek-chat')
  const [isLoading, setIsLoading] = useState(false)
  const [currentChatId, setCurrentChatId] = useState<string | null>(null)
  const [currentMessages, setCurrentMessages] = useState<ChatMessage[]>([])
  const [chatHistory, setChatHistory] = useState<Chat[]>([
    {
      id: '1',
      title: 'AI 助手介绍',
      updatedAt: new Date().toISOString(),
      messages: []
    },
    {
      id: '2',
      title: '代码生成问题',
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
      messages: []
    },
    {
      id: '3',
      title: '数据分析咨询',
      updatedAt: new Date(Date.now() - 172800000).toISOString(),
      messages: []
    }
  ])
  const [showUserMenu, setShowUserMenu] = useState(false)
  const messagesContainerRef = useRef<HTMLDivElement>(null)

  // 模拟用户信息
  const user: User = { username: '用户' }

  const sendMessage = async () => {
    if (!inputMessage.trim() || isLoading) return

    const userMessage = inputMessage.trim()
    setInputMessage('')
    setIsLoading(true)

    // 添加用户消息到界面
    const userMsg: ChatMessage = {
      id: crypto.randomUUID(),
      role: 'user',
      content: userMessage,
      timestamp: new Date().toISOString()
    }
    setCurrentMessages(prev => [...prev, userMsg])

    // 滚动到底部
    setTimeout(() => {
      scrollToBottom()
    }, 100)

    try {
      // 模拟API请求
      await new Promise(resolve => setTimeout(resolve, 1500))
      
      // 添加 AI 回复到界面
      const aiMsg: ChatMessage = {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: `这是对您消息的回复：${userMessage}。我是AI助手，可以帮助您解决各种问题。`,
        timestamp: new Date().toISOString()
      }
      setCurrentMessages(prev => [...prev, aiMsg])
    } catch (error) {
      console.error('发送失败:', error)
    } finally {
      setIsLoading(false)
      setTimeout(() => {
        scrollToBottom()
      }, 100)
    }
  }

  const startNewChat = () => {
    setCurrentChatId(null)
    setCurrentMessages([])
  }

  const selectChat = (chatId: string) => {
    setCurrentChatId(chatId)
    // 模拟加载聊天记录
    const chat = chatHistory.find(c => c.id === chatId)
    if (chat) {
      setCurrentMessages(chat.messages)
      setTimeout(() => {
        scrollToBottom()
      }, 100)
    }
  }

  const scrollToBottom = () => {
    if (messagesContainerRef.current) {
      messagesContainerRef.current.scrollTop = messagesContainerRef.current.scrollHeight
    }
  }

  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    const now = new Date()
    const diff = now.getTime() - date.getTime()
    const days = Math.floor(diff / (1000 * 60 * 60 * 24))

    if (days === 0) {
      return '今天'
    } else if (days === 1) {
      return '昨天'
    } else if (days < 7) {
      return `${days}天前`
    } else {
      return date.toLocaleDateString()
    }
  }

  const formatTime = (dateString: string) => {
    return new Date(dateString).toLocaleTimeString('zh-CN', {
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  const handleLogout = () => {
    console.log('退出登录')
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  return (
    <div className="chat-page min-h-screen bg-gradient-to-br from-purple-500 via-blue-500 to-purple-600 relative">
      {/* 背景动画层 */}
      <div className="absolute inset-0 bg-gradient-to-br from-purple-500/30 via-blue-500/30 to-purple-600/30 animate-pulse"></div>
      
      {/* 聊天主要内容 */}
      <main className="chat-main pt-16 relative z-10">
        <div className="chat-container max-w-7xl mx-auto h-screen flex">
          {/* 聊天历史侧边栏 */}
          <div className="chat-sidebar w-80 bg-white/90 backdrop-blur-lg border-r border-white/20 p-4">
            <div className="sidebar-header flex justify-between items-center mb-4">
              <h3 className="sidebar-title text-lg font-bold text-gray-900">聊天历史</h3>
              <button
                onClick={startNewChat}
                className="new-chat-btn px-3 py-1 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors text-sm"
              >
                ✨ 新对话
              </button>
            </div>
            
            <div className="chat-history space-y-2">
              {chatHistory.map((chat) => (
                <div
                  key={chat.id}
                  className={`chat-item p-3 rounded-lg cursor-pointer transition-colors ${
                    currentChatId === chat.id 
                      ? 'bg-blue-50 border border-blue-200' 
                      : 'hover:bg-gray-50'
                  }`}
                  onClick={() => selectChat(chat.id)}
                >
                  <div className="chat-title font-medium text-gray-900 truncate">{chat.title}</div>
                  <div className="chat-date text-sm text-gray-500">
                    {formatDate(chat.updatedAt)}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* 主聊天区域 */}
          <div className="chat-content flex-1 flex flex-col bg-white/80 backdrop-blur-lg">
            {/* 模型选择 */}
            <div className="model-selector p-4 bg-white/90 backdrop-blur-lg border-b border-gray-200">
              <div className="model-section flex items-center space-x-2">
                <span className="model-label text-gray-700 font-medium">🧠 AI 模型：</span>
                <select
                  value={selectedModel}
                  onChange={(e) => setSelectedModel(e.target.value)}
                  className="model-select px-3 py-1 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="deepseek-chat">🧠 DeepSeek Chat</option>
                </select>
              </div>
            </div>

            {/* 聊天消息区域 */}
            <div className="messages-area flex-1 p-4">
              <div
                ref={messagesContainerRef}
                className="messages-container h-full overflow-y-auto space-y-4 pr-2"
              >
                {currentMessages.map((message) => (
                  <div
                    key={message.id}
                    className={`message-wrapper flex ${
                      message.role === 'user' ? 'justify-end' : 'justify-start'
                    }`}
                  >
                    <div 
                      className={`message-bubble max-w-2xl px-4 py-3 rounded-2xl ${
                        message.role === 'user' 
                          ? 'bg-blue-500 text-white ml-auto' 
                          : 'bg-gray-100 text-gray-900'
                      }`}
                    >
                      <div className="message-content whitespace-pre-wrap">{message.content}</div>
                      <div className={`message-time text-xs mt-1 ${
                        message.role === 'user' ? 'text-blue-100' : 'text-gray-500'
                      }`}>
                        {formatTime(message.timestamp)}
                      </div>
                    </div>
                  </div>
                ))}
                
                {/* 加载指示器 */}
                {isLoading && (
                  <div className="loading-message flex justify-start">
                    <div className="message-bubble max-w-2xl px-4 py-3 rounded-2xl bg-gray-100 text-gray-900">
                      <div className="loading-content flex items-center space-x-2">
                        <div className="animate-spin w-4 h-4 border-2 border-blue-500 border-t-transparent rounded-full"></div>
                        <span>AI 正在思考...</span>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* 输入区域 */}
            <div className="input-area p-4 bg-white/90 backdrop-blur-lg border-t border-gray-200">
              <div className="input-container flex space-x-3">
                <textarea
                  value={inputMessage}
                  onChange={(e) => setInputMessage(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="输入您的消息..."
                  rows={3}
                  className="message-input flex-1 px-4 py-3 border border-gray-300 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
                <button
                  onClick={sendMessage}
                  disabled={!inputMessage.trim() || isLoading}
                  className="send-button px-6 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-medium"
                >
                  {isLoading ? '发送中...' : '🚀 发送'}
                </button>
              </div>
              <div className="input-hint text-xs text-gray-500 mt-2">
                按 Enter 发送，Shift + Enter 换行
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
